apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: talentmatch
          image: "talentmatch-ai:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: GEMINI_MODEL
              value: {{ .Values.geminiModel | default "gemini-2.5-flash" | quote }}
          envFrom:
            - secretRef:
                name: talentmatch-secret
