apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingressAnnotations }}
    {{- toYaml .Values.ingressAnnotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: talentmatch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
